using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace StarBase.Plc {



	public static class PLCMap_jst
    {
		static PLCMap_jst()
        {
			ALRAM_MSGS = new CHAM_ALARAM[7,16];
			ALRAM_MSGS[0,0]  = new CHAM_ALARAM ( ALARM_TYPE.ALARM_ERROR	,  "REVERSE PHASE ALARM"	);
			ALRAM_MSGS[0,1]  = new CHAM_ALARAM ( ALARM_TYPE.ALARM_ERROR	, "CHAMBER MAIN MC OFF"		, true);
			ALRAM_MSGS[0,2]  = new CHAM_ALARAM ( ALARM_TYPE.ALARM_ERROR	, "TR INPUT CP TRIP"		);
			ALRAM_MSGS[0,3]  = new CHAM_ALARAM ( ALARM_TYPE.ALARM_ERROR	, "TR OUTPUT CP TRIP"		);
			ALRAM_MSGS[0,4]  = new CHAM_ALARAM ( ALARM_TYPE.ALARM_ERROR	, "SMPS INPUT CP TRIP"		, true);
			ALRAM_MSGS[0,5]  = new CHAM_ALARAM ( ALARM_TYPE.ALARM_ERROR	, "SMPS OUTPUT CP TRIP"		, true);
			ALRAM_MSGS[0,6]  = new CHAM_ALARAM ( ALARM_TYPE.ALARM_ERROR	, "EMERGENCY ALARM"			, true);
			ALRAM_MSGS[0,7]  = new CHAM_ALARAM ( ALARM_TYPE.ALARM_WARNING	, "DOOR FAN CP TRIP"	);
			ALRAM_MSGS[0,8]  = new CHAM_ALARAM ( ALARM_TYPE.ALARM_ERROR	, "UPS POWER TRIP"			);
			ALRAM_MSGS[0,9]  = new CHAM_ALARAM ( ALARM_TYPE.ALARM_ERROR	, "AIR PRESSURE ALARM"		);
			ALRAM_MSGS[0,10] = new CHAM_ALARAM ( ALARM_TYPE.ALARM_ERROR	, "SMOKE SENSOR#1 ALARM"	, true);
			ALRAM_MSGS[0,11] = new CHAM_ALARAM ( ALARM_TYPE.ALARM_ERROR	, "SMOKE SENSOR#2 ALARM"	, true);
			ALRAM_MSGS[0,12] = new CHAM_ALARAM ( ALARM_TYPE.ALARM_ERROR	, "SMOKE SENSOR#3 ALARM"	, true);
			ALRAM_MSGS[0,13] = new CHAM_ALARAM ( ALARM_TYPE.ALARM_WARNING, "SIDE COVER DETECT"		);
			ALRAM_MSGS[0,14] = new CHAM_ALARAM ( ALARM_TYPE.ALARM_ERROR	, "SERVO TR CP TRIP"		);
			ALRAM_MSGS[0,15] = new CHAM_ALARAM ( ALARM_TYPE.ALARM_IGNORE, ""						);

			ALRAM_MSGS[1, 0] =  new CHAM_ALARAM(ALARM_TYPE.ALARM_WARNING, "RACK BIG COOLING FAN#1 STATE ");
			ALRAM_MSGS[1, 1] =  new CHAM_ALARAM(ALARM_TYPE.ALARM_WARNING, "RACK BIG COOLING FAN#2 STATE ");
			ALRAM_MSGS[1, 2] =  new CHAM_ALARAM(ALARM_TYPE.ALARM_WARNING, "RACK BIG COOLING FAN#3 STATE ");
			ALRAM_MSGS[1, 3] =  new CHAM_ALARAM(ALARM_TYPE.ALARM_WARNING, "RACK BIG COOLING FAN#4 STATE ");
			ALRAM_MSGS[1, 4] =  new CHAM_ALARAM(ALARM_TYPE.ALARM_WARNING, "RACK BIG COOLING FAN#5 STATE ");
			ALRAM_MSGS[1, 5] =  new CHAM_ALARAM(ALARM_TYPE.ALARM_WARNING, "RACK BIG COOLING FAN#6 STATE ");
			ALRAM_MSGS[1, 6] =  new CHAM_ALARAM(ALARM_TYPE.ALARM_WARNING, "RACK BIG COOLING FAN#7 STATE ");
			ALRAM_MSGS[1, 7] =  new CHAM_ALARAM(ALARM_TYPE.ALARM_WARNING, "RACK BIG COOLING FAN#8 STATE ");
			ALRAM_MSGS[1, 8] =  new CHAM_ALARAM(ALARM_TYPE.ALARM_WARNING, "RACK BIG COOLING FAN#9 STATE ");
			ALRAM_MSGS[1, 9] =  new CHAM_ALARAM(ALARM_TYPE.ALARM_WARNING, "RACK BIG COOLING FAN#10 STATE");
			ALRAM_MSGS[1, 10] = new CHAM_ALARAM(ALARM_TYPE.ALARM_WARNING, "RACK BIG COOLING FAN#11 STATE");
			ALRAM_MSGS[1, 11] = new CHAM_ALARAM(ALARM_TYPE.ALARM_WARNING, "RACK BIG COOLING FAN#12 STATE");
			ALRAM_MSGS[1, 12] = new CHAM_ALARAM(ALARM_TYPE.ALARM_IGNORE,  "");
			ALRAM_MSGS[1, 13] = new CHAM_ALARAM(ALARM_TYPE.ALARM_IGNORE,  "");
			ALRAM_MSGS[1, 14] = new CHAM_ALARAM(ALARM_TYPE.ALARM_IGNORE,  "");
			ALRAM_MSGS[1, 15] = new CHAM_ALARAM(ALARM_TYPE.ALARM_IGNORE,  "");


			ALRAM_MSGS[2, 0] = new CHAM_ALARAM(ALARM_TYPE.ALARM_WARNING, "RACK COOLING FAN#1 STATE   ");
			ALRAM_MSGS[2, 1] = new CHAM_ALARAM(ALARM_TYPE.ALARM_WARNING, "RACK COOLING FAN#2 STATE   ");
			ALRAM_MSGS[2, 2] = new CHAM_ALARAM(ALARM_TYPE.ALARM_WARNING, "RACK COOLING FAN#3 STATE   ");
			ALRAM_MSGS[2, 3] = new CHAM_ALARAM(ALARM_TYPE.ALARM_WARNING, "RACK COOLING FAN#4 STATE   ");
			ALRAM_MSGS[2, 4] = new CHAM_ALARAM(ALARM_TYPE.ALARM_WARNING, "RACK COOLING FAN#5 STATE   ");
			ALRAM_MSGS[2, 5] = new CHAM_ALARAM(ALARM_TYPE.ALARM_WARNING, "RACK COOLING FAN#6 STATE   ");
			ALRAM_MSGS[2, 6] = new CHAM_ALARAM(ALARM_TYPE.ALARM_WARNING, "RACK COOLING FAN#7 STATE  ");
			ALRAM_MSGS[2, 7] = new CHAM_ALARAM(ALARM_TYPE.ALARM_WARNING, "RACK COOLING FAN#8 STATE  ");
			ALRAM_MSGS[2, 8] = new CHAM_ALARAM(ALARM_TYPE.ALARM_WARNING, "RACK COOLING FAN#9 STATE  ");
			ALRAM_MSGS[2, 9] = new CHAM_ALARAM(ALARM_TYPE.ALARM_WARNING, "RACK COOLING FAN#10 STATE ");
			ALRAM_MSGS[2, 10] = new CHAM_ALARAM(ALARM_TYPE.ALARM_WARNING,"RACK COOLING FAN#11 STATE ");
			ALRAM_MSGS[2, 11] = new CHAM_ALARAM(ALARM_TYPE.ALARM_WARNING,"RACK COOLING FAN#12 STATE ");
			ALRAM_MSGS[2, 12] = new CHAM_ALARAM(ALARM_TYPE.ALARM_WARNING,"RACK COOLING FAN#13 STATE ");
			ALRAM_MSGS[2, 13] = new CHAM_ALARAM(ALARM_TYPE.ALARM_WARNING,"RACK COOLING FAN#14 STATE");
			ALRAM_MSGS[2, 14] = new CHAM_ALARAM(ALARM_TYPE.ALARM_WARNING,"RACK COOLING FAN#15 STATE");
			ALRAM_MSGS[2, 15] = new CHAM_ALARAM(ALARM_TYPE.ALARM_WARNING,"RACK COOLING FAN#16 STATE");

			ALRAM_MSGS[3, 0] = new CHAM_ALARAM( ALARM_TYPE.ALARM_ERROR,  "MAIN HEATER ELCB TRIP"			);
			ALRAM_MSGS[3, 1] = new CHAM_ALARAM( ALARM_TYPE.ALARM_ERROR,  "MAIN HEATER MC OFF"				);
			ALRAM_MSGS[3, 2] = new CHAM_ALARAM( ALARM_TYPE.ALARM_ERROR,  "MAIN HEATER SSR 60'C ALARM"		);
			ALRAM_MSGS[3, 3] = new CHAM_ALARAM( ALARM_TYPE.ALARM_ERROR,  "MAIN HEATER SSR 80'C ALARM"		);
			ALRAM_MSGS[3, 4] = new CHAM_ALARAM( ALARM_TYPE.ALARM_ERROR,  "MAIN HEATER EGO ALARM"			);
			ALRAM_MSGS[3, 5] = new CHAM_ALARAM( ALARM_TYPE.ALARM_ERROR,  "MAIN HEATER TEMP BIMETAL ALARM"	);
			ALRAM_MSGS[3, 6] = new CHAM_ALARAM( ALARM_TYPE.ALARM_ERROR,  "BLOWER MOTOR#1 CP TRIP"			);
			ALRAM_MSGS[3, 7] = new CHAM_ALARAM( ALARM_TYPE.ALARM_ERROR,  "BLOWER MOTOR#1 INV.OFF"			);
			ALRAM_MSGS[3, 8] = new CHAM_ALARAM( ALARM_TYPE.ALARM_ERROR,  "BLOWER MOTOR#2 CP TRIP"			);
			ALRAM_MSGS[3, 9] = new CHAM_ALARAM( ALARM_TYPE.ALARM_ERROR,  "BLOWER MOTOR#2 INV.OFF"			);
			ALRAM_MSGS[3, 10] = new CHAM_ALARAM(ALARM_TYPE.ALARM_ERROR,"BLOWER MOTOR INV ALARM"			);
			ALRAM_MSGS[3, 11] = new CHAM_ALARAM(ALARM_TYPE.ALARM_ERROR,"RACK IN LIMIT DETECT"				);
			ALRAM_MSGS[3, 12] = new CHAM_ALARAM(ALARM_TYPE.ALARM_ERROR,"RACK OUT LIMIT DETECT"			);
			ALRAM_MSGS[3, 13] = new CHAM_ALARAM(ALARM_TYPE.ALARM_ERROR,"COMP ELCB TRIP"					);
			ALRAM_MSGS[3, 14] = new CHAM_ALARAM(ALARM_TYPE.ALARM_ERROR,"COMP INVERTER OFF"				);
			ALRAM_MSGS[3, 15] = new CHAM_ALARAM(ALARM_TYPE.ALARM_ERROR, "COMP INVERTER ALARM");

			ALRAM_MSGS[4, 0] = new CHAM_ALARAM( ALARM_TYPE.ALARM_ERROR,	"COMP DPS LOW PRE.ALARM"	);
			ALRAM_MSGS[4, 1] = new CHAM_ALARAM( ALARM_TYPE.ALARM_ERROR,	"COMP DPS HIGH PRE.ALARM"	);
			ALRAM_MSGS[4, 2] = new CHAM_ALARAM( ALARM_TYPE. ALARM_ERROR,	"COMP FLOW ALARM"		);
			ALRAM_MSGS[4, 3] = new CHAM_ALARAM( ALARM_TYPE.ALARM_ERROR,	"COMP WPS ALARM"			);
			ALRAM_MSGS[4, 4] = new CHAM_ALARAM( ALARM_TYPE.ALARM_WARNING,  "COMP WATER FLOW ALARM"	);
			ALRAM_MSGS[4, 5] = new CHAM_ALARAM( ALARM_TYPE.ALARM_ERROR,	"COMP WATER LEAK ALARM"		);
			ALRAM_MSGS[4, 6] = new CHAM_ALARAM( ALARM_TYPE.ALARM_ERROR,	"SERVO CP POWER TRIP"		);
			ALRAM_MSGS[4, 7] = new CHAM_ALARAM( ALARM_TYPE.ALARM_ERROR,	"SERVO ALARM"				);
			ALRAM_MSGS[4, 8] = new CHAM_ALARAM( ALARM_TYPE.ALARM_ERROR,	"DOOR HEATER CP TRIP"		);
			ALRAM_MSGS[4, 9] = new CHAM_ALARAM( ALARM_TYPE.ALARM_WARNING,  "DOOR HEATER SSR 60'C ALARM");
			ALRAM_MSGS[4, 10] = new CHAM_ALARAM(ALARM_TYPE.ALARM_ERROR,	"DOOR HEATER SSR 80'C ALARM");
			ALRAM_MSGS[4, 11] = new CHAM_ALARAM(ALARM_TYPE.ALARM_ERROR,	"ETC HEATER MAIN ELCB TRIP"	);
			ALRAM_MSGS[4, 12] = new CHAM_ALARAM(ALARM_TYPE.ALARM_ERROR,	"ETC HEATER SSR 60'C ALARM"	);
			ALRAM_MSGS[4, 13] = new CHAM_ALARAM(ALARM_TYPE.ALARM_ERROR,	"ETC HEATER SSR 80'C ALARM"	);
			ALRAM_MSGS[4, 14] = new CHAM_ALARAM(ALARM_TYPE.ALARM_WARNING, "COMP LOW PRE.WARNING");
			ALRAM_MSGS[4, 15] = new CHAM_ALARAM(ALARM_TYPE.ALARM_WARNING, "COMP HIGH PRE.WARNING"   );

			ALRAM_MSGS[5, 0] = new CHAM_ALARAM( ALARM_TYPE.ALARM_ERROR,  "RAMP UP / DN LIMIT ALARM");
			ALRAM_MSGS[5, 1] = new CHAM_ALARAM( ALARM_TYPE.ALARM_ERROR, "COMP.IN TEMP ALARM");
			ALRAM_MSGS[5, 2] = new CHAM_ALARAM( ALARM_TYPE.ALARM_ERROR, "COMP.OUT TEMP ALARM");
			ALRAM_MSGS[5, 3] = new CHAM_ALARAM( ALARM_TYPE.ALARM_WARNING, "DOOR MOVING TIME OUT ALARM");
			ALRAM_MSGS[5, 4] = new CHAM_ALARAM( ALARM_TYPE.ALARM_WARNING, "RACK MOVING TIME OUT ALARM");
			ALRAM_MSGS[5, 5] = new CHAM_ALARAM( ALARM_TYPE.ALARM_WARNING, "SOAK TIME LIMIT ALARM");
			ALRAM_MSGS[5, 6] = new CHAM_ALARAM( ALARM_TYPE.ALARM_WARNING, "WATCH DOG ALARM");
			ALRAM_MSGS[5, 7] = new CHAM_ALARAM( ALARM_TYPE.ALARM_ERROR, "RACK IN SENSOR ERROR");
			ALRAM_MSGS[5, 8] = new CHAM_ALARAM( ALARM_TYPE.ALARM_WARNING, "LIGHT CURTAIN ALARM");
			ALRAM_MSGS[5, 9] = new CHAM_ALARAM( ALARM_TYPE.ALARM_WARNING, "DEVIATION HIGH ALARM");
			ALRAM_MSGS[5, 10] = new CHAM_ALARAM(ALARM_TYPE.ALARM_WARNING, "DEVIATION LOW ALARM");
			ALRAM_MSGS[5, 11] = new CHAM_ALARAM(ALARM_TYPE.ALARM_WARNING, "RAMP UP / DN LIMIT WARNING");
			ALRAM_MSGS[5, 12] = new CHAM_ALARAM(ALARM_TYPE.ALARM_ERROR,		"LOW TEMP ALARM"		, true);
			ALRAM_MSGS[5, 13] = new CHAM_ALARAM(ALARM_TYPE.ALARM_ERROR,		"HIGH TEMP ALARM"		, true);
			ALRAM_MSGS[5, 14] = new CHAM_ALARAM(ALARM_TYPE.ALARM_ERROR,		"OVER TEMP ALARM"		, true);
			ALRAM_MSGS[5, 15] = new CHAM_ALARAM(ALARM_TYPE.ALARM_IGNORE, "");

			ALRAM_MSGS[6, 0] = new CHAM_ALARAM(ALARM_TYPE.ALARM_ERROR,  "SYSTEM AC ERROR");
			ALRAM_MSGS[6, 1] = new CHAM_ALARAM(ALARM_TYPE.ALARM_ERROR, "SYSTEM 48V SMPS1 ERROR"		, true);
			ALRAM_MSGS[6, 2] = new CHAM_ALARAM(ALARM_TYPE.ALARM_ERROR, "SYSTEM 48V SMPS2 ERROR"		, true);
			ALRAM_MSGS[6, 3] = new CHAM_ALARAM(ALARM_TYPE.ALARM_ERROR, "SYSTEM 48V SMPS3 ERROR"		, true);
			ALRAM_MSGS[6, 4] = new CHAM_ALARAM(ALARM_TYPE.ALARM_ERROR, "SYSTEM 48V SMPS4 ERROR"		, true);
			ALRAM_MSGS[6, 5] = new CHAM_ALARAM(ALARM_TYPE.ALARM_ERROR, "COMP.IN TEMP WARNING");
			ALRAM_MSGS[6, 6] = new CHAM_ALARAM(ALARM_TYPE.ALARM_ERROR, "COMP.OUT TEMP WARNING");
			ALRAM_MSGS[6, 7] = new CHAM_ALARAM(ALARM_TYPE.ALARM_ERROR, "DOOR OPEN STATUS RUN ERROR");
			ALRAM_MSGS[6, 8] = new CHAM_ALARAM(ALARM_TYPE.ALARM_IGNORE, "");
			ALRAM_MSGS[6, 9] = new CHAM_ALARAM(ALARM_TYPE.ALARM_IGNORE, "");
			ALRAM_MSGS[6, 10] = new CHAM_ALARAM(ALARM_TYPE.ALARM_IGNORE, "");
			ALRAM_MSGS[6, 11] = new CHAM_ALARAM(ALARM_TYPE.ALARM_IGNORE, "");
			ALRAM_MSGS[6, 12] = new CHAM_ALARAM(ALARM_TYPE.ALARM_IGNORE, "");
			ALRAM_MSGS[6, 13] = new CHAM_ALARAM(ALARM_TYPE.ALARM_IGNORE, "");
			ALRAM_MSGS[6, 14] = new CHAM_ALARAM(ALARM_TYPE.ALARM_IGNORE, "");
			ALRAM_MSGS[6, 15] = new CHAM_ALARAM(ALARM_TYPE.ALARM_IGNORE, "");
		}

		public static int AlramCount = 7;
		public static CHAM_ALARAM[,] ALRAM_MSGS;

		public static int PLC_RD_PV_W = 1100;

		public static int PLC_WT_SV_W = 1103;
		public static int PLC_RD_SV_W = 1101;

		public static int PLC_RD_STAT_W = 60;
		// 0 bit: Temp Run Mode						
		// 1 bit: Temp Ambient Mode  	
		// 2 bit: Temp Stop Mode				
		// 3 bit: Door Open 	
		// 4 bit: DoorClose
		// 5 bit: Remote Mode 0=remote 1=local
		// 6 bit: Rack Detect
		// 7 bit: Alarm Detect
		// 8 bit: Rack In Comp						
		// 9 bit: Rack Out Comp
		// 10bit: PV Temp Maintain 
		// 11 bit: System Power On
		public static int PLC_RD_LAMP1_W = 70;
		public static int PLC_RD_LAMP2_W = 71;


		public static int PLC_WT_RUN_I = 100;
		public static int PLC_WT_AMBI_I = 101;
		public static int PLC_WT_STOP_I = 102;
		
		public static int PLC_WT_DOOROPEN_I = 103;
		public static int PLC_WT_DOORCLOSE_I = 104;

		public static int PLC_WT_RACKIN_I = 105;
		public static int PLC_WT_RACKOUT_I = 106;
		public static int PLC_WT_REMOTE_I = 107; // temp-control remote mode trigger.
		public static int PLC_WT_RESET_I = 108;

		// AMP 관련
		public static int PLC_RW_LAMP_CTRL_I = 109;   // 1 = OS CTRL
		public static int PLC_RW_LAMP_R_I = 110;
		public static int PLC_RW_LAMP_Y_I = 111;
		public static int PLC_RW_LAMP_G_I = 112;
		public static int PLC_RW_LAMP_ALL_I = 113;
		public static int PLC_RW_BUZZER_I = 114;
		public static int PLC_RW_LAMP_R_BLINK_I = 115;
		public static int PLC_RW_LAMP_Y_BLINK_I = 116;
		public static int PLC_RW_LAMP_G_BLINK_I = 117;

		public static int PLC_WT_SYSERR_I = 118; // 0x0100 : System Error On
		
		//NIT Setting
		public static int PLC_WT_HITEMP_W = 1210;
		public static int PLC_WT_LOWTEMP_W = 1220;
		public static int PLC_WT_OVERTEMP_W = 1221;


		//Watch Dog
		public static int PLC_WT_WATCH_TIME_W = 900;
		public static int PLC_WT_WATCH_TOGGLE_W = 901;
		public static int PLC_WT_WATCH_ENABLE_W = 902;


		//RAM 관련
		public static int PLC_RD_SYS_ALARM1_W = 80;
		public static int PLC_RD_SYS_ALARM2_W = 81;
		public static int PLC_RD_SYS_ALARM3_W	=	82;
		public static int PLC_RD_SYS_ALARM4_W	=	84;
		public static int PLC_RD_SYS_ALARM5_W	=	85;
		public static int PLC_RD_SYS_ALARM6_W	=	86;
		
		public static int PLC_RD_POWER_ALARM_W = 8;


	}
}
