domain_path: /home/work/jzxu/nbiex/logic/st805ex_ctrl/vitis/st805ex_platform/export/st805ex_platform/sw/standalone_microblaze_0
app_src_dir: /home/tools/Xilinx/2025.2/Vitis/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
lang: c
